spring:
  application:
    name: icon-service

  profiles:
    active: ${PROFILE}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/test_icon?serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_catalog: test_icon
    open-in-view: false

  h2:
    console:
      enabled: true

security:
  cors:
    paths:
      - ${APP_FRONT}
      - ${CREATOR_FRONT}
      - ${ADMIN_FRONT}

springdoc:
  swagger-ui:
    path: /api-docs/icon/index.html
#    enabled: true
#    url: /docs/openapi3.json
#    path: /icon-docs/v1/api-docs/index.html